---
title: "COVID-19 State Data"
author: "Patrick Aselin"
date: "3/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library Imports
```{r}
library(rvest)
library(dplyr)
library(ggplot2)
library(readxl)
```



# Data Imports

```{r}
nst_est2019 <- read_excel("nst-est2019.xlsx", skip = 3)
```


```{r}
ma_data <- xml2::read_html("https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Vermont")
```

## Get List of URLs
```{r}
us_cv_data <- xml2::read_html("https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_the_United_States")
us_cv_data <- us_cv_data %>%
  html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[41]/div[2]/table") %>%
  html_table(fill = TRUE) %>%
  magrittr::extract2(1)
```


# Data Cleaning Procedure

```{r}
ma_data %>%
  html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[3]/div/table") %>%
  html_table() %>%
  magrittr::extract2(1)
```


```{r}
ma_cases <- ma_data %>%
  html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[3]/div/table") %>%
  html_table() %>%
  magrittr::extract2(1)
```



```{r}
colnames(ma_cases) <- c(ma_cases[1,])
ma_cases <- ma_cases[-c(1),-c(1,3)]
```

```{r}
ma_cases <- ma_cases %>%
  mutate(Date = as.Date(Date))
```

```{r}
# if a row in the Cases column has an = sign, make the Date equal to the last date + 1, assuming that the first row exists
rows_where_cases_unchanged <- grep("=", ma_cases$`# of cases`)
for (i in rows_where_cases_unchanged){
  ma_cases$Date[i] <- ma_cases$Date[i-1] + 1
}
```


```{r}
# first replace all commas with ""
ma_cases$`# of cases` <- gsub(",","", as.character(ma_cases$`# of cases`))
ma_cases$`# of deaths` <- gsub(",","", as.character(ma_cases$`# of deaths`))
# remove text in parentheses and including the parentheses
ma_cases$`# of cases` <- as.numeric(gsub("\\s*\\([^\\)]+\\)\\s*$","", ma_cases$`# of cases`))
ma_cases$`# of deaths` <- as.numeric(gsub("\\s*\\([^\\)]+\\)\\s*$","", ma_cases$`# of deaths`))
```

```{r}
# drop rows that are all na 
ma_cases <- ma_cases[rowSums(is.na(ma_cases)) != ncol(ma_cases), ]
# set all NAs to 0
ma_cases[is.na(ma_cases)] <- 0
```

```{r}
ma_cases$State <- "MA"
```

# Wrap as a Function

```{r}
get_and_process_states <- function(x){
  # get wikipedia site
  state_data <- xml2::read_html(paste0("https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_", x))
  
  # get the state name
  state_name_cleaned <- stringr::str_trim(gsub("_", " ", gsub("\\s*\\([^\\)]+\\)\\s*$","", x)))
  
  # pull the table of interest out of the page
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[3]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[2]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[1]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[5]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[4]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath =  "/html/body/div[3]/div[3]/div[4]/div/div[6]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath =  "/html/body/div[3]/div[3]/div[4]/div/div[4]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath =  "/html/body/div[3]/div[3]/div[4]/div/div[4]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  
  # choose the first item from the list 
  state_data <- state_data[-c(dim(state_data)[1]), -c(1,3)]
  colnames(state_data) <- unique(as.character(state_data[1,]))
  if (length(which(names(state_data) %in% c(NA))) > 0){
    state_data <- state_data[-c(1), -which(names(state_data) %in% c(NA))]
  } else {
    state_data <- state_data[-c(1), ]
  }
  
  state_data <- state_data %>%
    mutate(Date = as.Date(Date)) %>%
    filter(!is.na(Date))
  
  # if a row in the Cases column has an = sign, make the Date equal to the last date + 1, assuming that the first row exists
  # rows_where_cases_unchanged <- union(grep("=", state_data$`# of cases`), grep("n.a.", state_data$`# of cases`))
  # for (i in rows_where_cases_unchanged){
  #  state_data$Date[i] <- state_data$Date[i-1] + 1
  # }
  
  
  # first replace all commas with ""
  state_data$`# of cases` <- gsub(",","", as.character(state_data$`# of cases`))
  try(state_data$`# of deaths` <- gsub(",","", as.character(state_data$`# of deaths`)))
  
  # remove text after and including the first parenthesis
  state_data$`# of cases` <- as.numeric(gsub("\\(.*","", state_data$`# of cases`))
  try(state_data$`# of deaths` <- as.numeric(gsub("\\(.*","", state_data$`# of deaths`)))
  
  # drop rows that are all na 
  state_data <- state_data[rowSums(is.na(state_data)) != ncol(state_data), ]
  
  # set all NAs to 0
  state_data[is.na(state_data)] <- 0
  if (state_name_cleaned %in% state.name){
    state_data$State <- state.abb[grep(state_name_cleaned, state.name)]
  } else {
    state_data$State <- state_name_cleaned
  }
  
  # return data
  return(state_data)
}
```


# Unit Tests
```{r}
get_and_process_states("Washington_(state)")
get_and_process_states("New_York_(state)")
get_and_process_states("Vermont")
get_and_process_states("New_Hampshire")
get_and_process_states("California")
get_and_process_states("Louisiana")
get_and_process_states("Washington,_D.C.")
get_and_process_states("Colorado")
```


# Study Unit Test

```{r}
state_data <- xml2::read_html("https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Colorado")

#state_data <- state_data %>%
#  html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[4]/div/table") %>%
#  html_table() 
try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[3]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[2]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[1]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[5]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath = "/html/body/div[3]/div[3]/div[4]/div/div[4]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath =  "/html/body/div[3]/div[3]/div[4]/div/div[6]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath =  "/html/body/div[3]/div[3]/div[4]/div/div[4]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
  try(state_data <- state_data %>%
    html_nodes(xpath =  "/html/body/div[3]/div[3]/div[4]/div/div[4]/div/table") %>%
    html_table() %>%
    magrittr::extract2(1))
```

```{r}
state_data <- state_data[-c(dim(state_data)[1]),-c(1,3)]
colnames(state_data) <- unique(as.character(state_data[1,]))
if (length(which(names(state_data) %in% c(NA))) > 0){
  state_data <- state_data[-c(1), -which(names(state_data) %in% c(NA))]
} else {
  state_data <- state_data[-c(1),]
}


#state_data <- state_data %>%
#  mutate(Date = as.Date(Date))
state_data <- state_data %>%
    mutate(Date = as.Date(Date)) %>%
    filter(!is.na(Date))

# if a row in the Cases column has an = sign, make the Date equal to the last date + 1, assuming that the first row exists
#rows_where_cases_unchanged <- union(grep("=", state_data$`# of cases`), grep("n.a.", state_data$`# of cases`))
#for (i in rows_where_cases_unchanged){
#  state_data$Date[i] <- state_data$Date[i-1] + 1
#}

# first replace all commas with ""
state_data$`# of cases` <- gsub(",","", as.character(state_data$`# of cases`))
state_data$`# of deaths` <- gsub(",","", as.character(state_data$`# of deaths`))
# remove text in parentheses and including the parentheses
state_data$`# of cases` <- as.numeric(gsub("\\(.*","", state_data$`# of cases`))
state_data$`# of deaths` <- as.numeric(gsub("\\(.*","", state_data$`# of deaths`))

# drop rows that are all na 
state_data <- state_data[rowSums(is.na(state_data)) != ncol(state_data), ]
# set all NAs to 0
state_data[is.na(state_data)] <- 0

state_data$State <- "MA"
```

# Clean Census Data
```{r}
names(nst_est2019)[1] <- "State"
nst_est2019 <- nst_est2019[-c(1:5),]
nst_est2019$State <- gsub('^\\.', '', nst_est2019$State)
nst_est2019 <- nst_est2019[-c(52:58),]
nst_est2019 <- nst_est2019 %>%
  select("State", `2019`)
```

```{r}
replace_w_abb <- function(x){
  if(x == "Washington,_D.C."){
    "Washington, D.C."
  } else {
    state.abb[grep(x, state.name)][1]
  }
}
```

```{r}
nst_est2019$State <- sapply(nst_est2019$State, replace_w_abb, simplify = TRUE, USE.NAMES = FALSE)
```



# Build Dataset
```{r}
available_states = c('Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia_(U.S._state)', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New_Hampshire', 'New_Jersey', 'New_Mexico', 'New_York_(state)', 'North_Carolina', 'North_Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode_Island', 'South_Carolina', 'South_Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', "Washington_(state)", "Washington,_D.C.", 'West_Virginia', 'Wisconsin', 'Wyoming')
```

```{r message=FALSE, warning=FALSE}
master_state_data <- list()
for (state in available_states){
  master_state_data[[state]] <- get_and_process_states(state)
}
```


```{r}
master_data <- data.table::rbindlist(master_state_data, fill = TRUE)
```

```{r}
# master_data[is.na(master_data)] <- NA
master_data$deaths <- as.numeric(master_data$deaths)
master_data$deaths[is.na(master_data$deaths)] <- 0
```

merge # deaths and deaths column

```{r}
cleaned_data <- master_data %>%
  mutate(`# of deaths` = `# of deaths` + deaths) %>%
  select(-deaths)
```

merge covid data and population data
```{r}
cleaned_data <- cleaned_data %>%
  inner_join(nst_est2019, by = "State")
```



```{r}
saveRDS(cleaned_data, "cleaned_data.rds")
write.csv(cleaned_data, "cleaned_data.csv")
```

# Visualizations

```{r}
cleaned_data %>%
  group_by(State) %>%
  summarise(total_case = max(`# of cases`)) %>%
  arrange(-total_case) %>%
  top_n(20, total_case) %>%
  ggplot(aes(x = reorder(State, total_case), y = total_case)) +
  geom_col() +
  theme_bw() + 
  coord_flip() +
  ylab("Total Number of Cases") +
  xlab("State") +
  ggtitle("Total Number of COVID-19 Cases in the 20 States with the Most Infections") + 
  theme(plot.title = element_text(hjust = 0.5))

cleaned_data %>%
  group_by(State) %>%
  summarise(total_deaths = max(`# of deaths`)) %>%
  arrange(-total_deaths) %>%
  top_n(20, total_deaths) %>%
  ggplot(aes(x = reorder(State, total_deaths), y = total_deaths)) +
  geom_col() +
  theme_bw() + 
  coord_flip() +
  ylab("Total Number of Deaths") +
  xlab("State") +
  ggtitle("Total Number of COVID-19 Deaths in the 20 States with the Most Fatalities") + 
  theme(plot.title = element_text(hjust = 0.5))

cleaned_data %>%
  group_by(State) %>%
   summarise(total_deaths = max(`# of deaths`),
         total_cases = max(`# of cases`)) %>%
  filter(total_deaths > 0) %>%
  mutate(fatality_rate = total_deaths/total_cases*100) %>%
  arrange(-fatality_rate) %>%
  top_n(20, fatality_rate) %>%
  ggplot(aes(x = reorder(State, fatality_rate), y = fatality_rate)) +
  geom_col() +
  theme_bw() + 
  coord_flip() +
  ylab("%Fatalities") +
  xlab("State") +
  ggtitle("%Fatalities for the 20 States with the Highest %Fatalities") + 
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
cleaned_data %>%
  group_by(State) %>%
  summarise(total_deaths = max(`# of deaths`),
         total_cases = max(`# of cases`)) %>%
  ggplot(aes(x = total_cases, y = total_deaths, colour = State)) +
  geom_point() +
  theme_bw()
plotly::ggplotly()
```




```{r}
cleaned_data %>%
  filter(`# of cases` > 0) %>%
  #filter(Date >= as.Date("2020-03-10")) %>%
  ggplot(aes(x = Date, y = `# of cases`, colour = State)) +
  geom_line() +
  theme_bw()
plotly::ggplotly()
```



```{r}
cleaned_data %>%
  filter(`# of cases` > 0) %>%
  #filter(Date >= as.Date("2020-03-10")) %>%
  ggplot(aes(x = Date, y = `# of deaths`, colour = State)) +
  geom_line() +
  theme_bw()
```












